name: github pages

on:
  push:
    branches:
      - main
env:
  REACT_APP_API_KEY: "${{ secrets.REACT_APP_API_KEY }}"
  REACT_APP_AUTH_DOMAIN: "${{ secrets.REACT_APP_AUTH_DOMAIN }}"
  REACT_APP_DATABASE_URL: "${{ secrets.REACT_APP_DATABASE_URL }}"
  REACT_APP_PROJECT_ID: "${{ secrets.REACT_APP_PROJECT_ID }}"
  REACT_APP_STORAGE_BUCKET: "${{ secrets.REACT_APP_STORAGE_BUCKET }}"
  REACT_APP_MESSAGIN_ID: "${{ secrets.REACT_APP_MESSAGIN_ID }}"
  REACT_APP_APP_ID: "${{ secrets.REACT_APP_APP_ID }}"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "12.x"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
